# Site
repository: wilson96wu/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wilson Wu
title: Tech Lead
email: wilson96wu@gmail.com


# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: yanhao-wu-64131a61
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am currently working as a **Senior Developer Level 2/Tech Lead** in the Gaming Industry. I gained my master's degree in computer science in 2007. Worked as full stack developer from 2007 to 2009 by building intelligent building management systems with C++ and SQL. In 2009, I joined the gaming industry, became a front-end developer working on C++, ActionScript, JavaScript, and typescript. I created my first game engine in 2012, which became one of the most successful and long-standing game engines in our company. More than a hundred games have been developed on this engine, including many of our company's legendary games. This engine is still in use today in 2022. 
  
  Since 2019, I have been working on a new game engine focused on fast development and maintainability. For fast delivery, we build our engine on top of Cocos Creator to utilize its UI Editing and templating capability. For maintainability, we focus on re-usability, unit testing and automation, aiming to use a single code base to drive a large number of games. Currently, the entire department is adopting this new engine. For some of our games, we are able to reduce our development time from 3 months to a week.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Games Global
        link: gamesglobal.com
        # link_text: boringcompany.com
        sub_title: Senior Developer Level 2/Tech Lead
        caption: September 2021 - Present       
        description: | # this will include new lines to allow paragraphs
            Guiding the technical direction and architecture design of game engine.

            Leading a group of Develops design/develop components, data layer, automation.

            Looking into migration of our engine infrastructure to AWS.

            On boarding and mentoring new developers and developers from other team.

            Create a "best idea wins" culture in the team.

 
      - layout: left
        border: weak
        title: Derivco
        link: derivco.co.za
        # link_text: boringcompany.com
        sub_title: Senior Developer Level 1
        caption: July 2013 - September 2021       
        description: |
            I have Worked on different products in various teams across the company
            
            Improving development process, creating tool to facilitate code/branch merging

            Helping other teams to improve game performance

            Helping other teams to solve difficult problems

            Leading technical guild, initiate technical innovation. code review            

            
      - layout: left
        border: weak
        title: Derivco
        link: derivco.co.za
        # link_text: boringcompany.com
        sub_title: Software Developer Level 2
        caption: November 2009 - July 2013
        description: |
            Working on various games on different technologies, C++, Actionscript on Adobe Flash in the beginning.

            As the company's focus shift to mobile in 2012, I worked on JavaScript, HTML5 and CSS.

            In earlier days, browser and Javascript is not as powerful, I had to learning how to write effeicent code to run game in the browser.

      
      - layout: left       
        title: Scansoft Technologies
        link: scansoft.co.za
        # link_text: boringcompany.com
        sub_title: Full stack Developer
        caption: July 2007 - October 2009
        description: |
            Working on Intelligent Building Management System (IBMS) with VC++ .net and SQL.

            Working in a small company enables me to working on entire technologies stack. I worked on hardware driver, Database design, Client development with various open source libraries.

            I also gained precious experience of interacting directly with our Clients: City of Capetown, Old Mutual, Sanlam, Shell and Engen.

  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of the Western Cape
        caption: 2003 - 2006
        sub_title: MSc Computer Science        
        description: | # this will include new lines to allow paragraphs
          I worked on earlier days of **Voice over Internet Protocol** technology

          Focusing on enhancing the Session Initiation Protocol Presence model to protect sensitive geographic information which can be easily integrated into IP telephony services in order to reducing users' privacy concerns and increasing the user satisfaction.
          
          I have been granted with **Center of Excellence scholarship** and graduated with **Cum Laude**

  - title: Extra activities
    layout: text
    caption: 2022
    content: | # this will include new lines to allow paragraphs
      Presented on Engine development on **Game Development Conference** at **International Convention Centre**, Durban

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
